"use client";
import {detectActionKind} from "@/lib/action-kind";
type Props={goal:string;value:string;onChange:(value:string)=>void};
function parse(value:string){try{return value.trim()?JSON.parse(value) as Record<string,unknown>:{};}catch{return {};}}
export default function ActionDetailsFields({goal,value,onChange}:Props){
  const kind=detectActionKind(goal);if(!kind)return null;const data=parse(value);
  const set=(key:string,next:string)=>onChange(JSON.stringify({...data,[key]:next},null,2));
  if(kind==="email")return <fieldset><legend>Email details</legend><label>To</label><input value={String(data.to??"")} onChange={e=>set("to",e.target.value)}/><label>Subject</label><input value={String(data.subject??"")} onChange={e=>set("subject",e.target.value)}/><label>Body</label><textarea value={String(data.body??"")} onChange={e=>set("body",e.target.value)}/></fieldset>;
  if(kind==="calendar")return <fieldset><legend>Calendar details</legend><label>Action</label><select value={String(data.action??"create")} onChange={e=>set("action",e.target.value)}><option value="create">Create event</option><option value="update">Update event</option><option value="cancel">Cancel event</option></select><label>Title</label><input value={String(data.title??"")} onChange={e=>set("title",e.target.value)}/><label>Start</label><input type="datetime-local" value={String(data.start??"")} onChange={e=>set("start",e.target.value)}/><label>End</label><input type="datetime-local" value={String(data.end??"")} onChange={e=>set("end",e.target.value)}/><label>Description</label><textarea value={String(data.description??"")} onChange={e=>set("description",e.target.value)}/></fieldset>;
  if(kind==="github")return <fieldset><legend>GitHub action details</legend><label>Action</label><input value={String(data.action??"")} onChange={e=>set("action",e.target.value)} placeholder="create_issue"/><label>Title</label><input value={String(data.title??"")} onChange={e=>set("title",e.target.value)}/><label>Body</label><textarea value={String(data.body??"")} onChange={e=>set("body",e.target.value)}/></fieldset>;
  return <fieldset><legend>Database action details</legend><label>Operation</label><input value={String(data.operation??"")} onChange={e=>set("operation",e.target.value)} placeholder="create_memory"/><label>Content</label><textarea value={String((data.values as Record<string,unknown>|undefined)?.content??"")} onChange={e=>onChange(JSON.stringify({...data,values:{...((data.values as Record<string,unknown>|undefined)??{}),content:e.target.value}},null,2))}/></fieldset>;
}
