"use client";
import {detectActionKind} from "@/lib/action-kind";
type Props={goal:string;value:string;onChange:(value:string)=>void};
function parse(value:string){try{return value.trim()?JSON.parse(value) as Record<string,unknown>:{};}catch{return {};}}
function localToIso(value:string){if(!value)return "";const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toISOString();}
function isoToLocal(value:unknown){if(typeof value!=="string"||!value)return "";const date=new Date(value);if(Number.isNaN(date.getTime()))return value;const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16);}
export default function ActionDetailsFields({goal,value,onChange}:Props){
  const kind=detectActionKind(goal);if(!kind)return null;const data=parse(value);
  const set=(key:string,next:unknown)=>onChange(JSON.stringify({...data,[key]:next},null,2));
  if(kind==="email")return <fieldset><legend>Email details</legend><label>To</label><input type="email" value={String(data.to??"")} onChange={e=>set("to",e.target.value)}/><label>Subject</label><input maxLength={200} value={String(data.subject??"")} onChange={e=>set("subject",e.target.value)}/><label>Body</label><textarea maxLength={20000} value={String(data.body??"")} onChange={e=>set("body",e.target.value)}/></fieldset>;
  if(kind==="calendar"){const action=String(data.action??"create");return <fieldset><legend>Calendar details</legend><label>Action</label><select value={action} onChange={e=>set("action",e.target.value)}><option value="create">Create event</option><option value="update">Update event</option><option value="delete">Delete event</option></select>{action!=="create"&&<><label>Event ID</label><input value={String(data.eventId??"")} onChange={e=>set("eventId",e.target.value)} required/></>}{action!=="delete"&&<><label>Title</label><input maxLength={200} value={String(data.title??"")} onChange={e=>set("title",e.target.value)}/><label>Start</label><input type="datetime-local" value={isoToLocal(data.start)} onChange={e=>set("start",localToIso(e.target.value))}/><label>End</label><input type="datetime-local" value={isoToLocal(data.end)} onChange={e=>set("end",localToIso(e.target.value))}/><label>Description</label><textarea maxLength={10000} value={String(data.description??"")} onChange={e=>set("description",e.target.value)}/></>}</fieldset>;}
  if(kind==="github"){const params=(data.params&&typeof data.params==="object"&&!Array.isArray(data.params)?data.params:{}) as Record<string,unknown>;const action=String(data.action??"create_issue");const setParam=(key:string,next:string|number)=>onChange(JSON.stringify({...data,params:{...params,[key]:next}},null,2));return <fieldset><legend>GitHub action details</legend><label>Repository</label><input value={String(data.repository??"")} onChange={e=>set("repository",e.target.value)} placeholder="owner/repository"/><label>Action</label><select value={action} onChange={e=>onChange(JSON.stringify({...data,action:e.target.value,params:{}},null,2))}><option value="create_issue">Create issue</option><option value="comment_issue">Comment on issue</option><option value="create_branch">Create branch</option><option value="create_file">Create file</option><option value="update_file">Update file</option></select>{action==="create_issue"&&<><label>Title</label><input maxLength={256} value={String(params.title??"")} onChange={e=>setParam("title",e.target.value)}/><label>Body</label><textarea value={String(params.body??"")} onChange={e=>setParam("body",e.target.value)}/></>}{action==="comment_issue"&&<><label>Issue number</label><input type="number" min={1} value={String(params.issueNumber??"")} onChange={e=>setParam("issueNumber",Number(e.target.value))}/><label>Comment</label><textarea value={String(params.body??"")} onChange={e=>setParam("body",e.target.value)}/></>}{action==="create_branch"&&<><label>New branch</label><input value={String(params.branch??"")} onChange={e=>setParam("branch",e.target.value)}/><label>Source ref</label><input value={String(params.from??"main")} onChange={e=>setParam("from",e.target.value)}/></>}{(action==="create_file"||action==="update_file")&&<><label>Path</label><input value={String(params.path??"")} onChange={e=>setParam("path",e.target.value)}/><label>Branch</label><input value={String(params.branch??"main")} onChange={e=>setParam("branch",e.target.value)}/><label>Content</label><textarea value={String(params.content??"")} onChange={e=>setParam("content",e.target.value)}/>{action==="update_file"&&<><label>Current file SHA</label><input value={String(params.sha??"")} onChange={e=>setParam("sha",e.target.value)}/></>}</>}</fieldset>;}
    const values=(data.values&&typeof data.values==="object"&&!Array.isArray(data.values)?data.values:{}) as Record<string,unknown>;const operation=String(data.operation??"insert");const updateValues=(next:Record<string,unknown>)=>onChange(JSON.stringify({...data,table:"memories",operation,values:{...values,...next}},null,2));
  return <fieldset><legend>Memory details</legend><label>Operation</label><select value={operation} onChange={e=>onChange(JSON.stringify({...data,table:"memories",operation:e.target.value,values},null,2))}><option value="insert">Create memory</option><option value="update">Update memory</option></select>{operation==="update"&&<><label>Memory ID</label><input value={String(data.id??"")} onChange={e=>set("id",e.target.value)}/></>}<label>Kind</label><select value={String(values.kind??"working")} onChange={e=>updateValues({kind:e.target.value})}><option value="working">Working</option><option value="project">Project</option><option value="long_term">Long term</option></select><label>Content</label><textarea maxLength={8000} value={String(values.content??"")} onChange={e=>updateValues({content:e.target.value})}/><label>Status</label><select value={String(values.status??"candidate")} onChange={e=>updateValues({status:e.target.value})}><option value="candidate">Candidate</option><option value="active">Active</option></select></fieldset>;
}
